### PR TITLE
Fail if dictionaries have missing *or wrong* type

### LINKED ISSUE #407: Dictionary with wrong "type" can be submitted
Steps to reproduce:
1. Sign in to AMO-dev page https://addons-dev.allizom.org/en-US/
2. Submit a dictionary with a wrong "type" set (i.e. type=2)

Expected results:
The dictionary cannot be submitted because the "type" is wrong.

Actual results:
The dictionary can be submitted.

Notes/Issues:
Verified on AMO-dev FF45(Win 7).
Screenshot for this issue:

### PR DESCRIPTION
**Pull request by wagnerand**
This fixes #407

@EnTeQuAk r?

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
I kinda would love to see a test for the scenario that fails if that's possible.

**Comment by wagnerand** [comment]
Added a test. The other changes in the test file are just cosmetics.

**Comment by EnTeQuAk** [comment]
r+

**Comment by wagnerand** [comment]
Thank you!

**Pull request merged**
