### PR TITLE
Noseless tests

### PR DESCRIPTION
**Pull request by wagnerand**
Let's see what travis says...

### CODE REVIEW

**Comment by wagnerand** [comment]
@diox I moved the contents of `functional_tests` to `tests`. Now that functional test class fails, with `InvocationError`. Can you make anything out of that?

**Comment by wagnerand** [comment]
Ah, running `tox` locally gives me:
```
...
tests/test_validator.py ................................FFF.....
...
============================================================================================================== FAILURES ==============================================================================================================
_______________________________________________________________________________________________ SearchTools.test_opensearch_providers ________________________________________________________________________________________________

self = <tests.test_validator.SearchTools testMethod=test_opensearch_providers>

    def test_opensearch_providers(self):
        self.validate('sms_search-20110115 .xml')
>       self.expectMsg(u'OpenSearch: <Url> elements may not be rel=self')

tests/test_validator.py:291:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.test_validator.SearchTools testMethod=test_opensearch_providers>, msg = 'OpenSearch: <Url> elements may not be rel=self'

    def expectMsg(self, msg):
>       assert msg in self.messages, (
                    'Expected %r but only got %r' % (msg, self.messages))
E       AssertionError: Expected u'OpenSearch: <Url> elements may not be rel=self' but only got [u'Test']
E       assert 'OpenSearch: <Url> elements may not be rel=self' in ['Test']
E        +  where ['Test'] = <tests.test_validator.SearchTools testMethod=test_opensearch_providers>.messages

tests/test_validator.py:107: AssertionError
_______________________________________________________________________________________________ SearchTools.test_opensearch_shortname ________________________________________________________________________________________________

self = <tests.test_validator.SearchTools testMethod=test_opensearch_shortname>

    def test_opensearch_shortname(self):
        self.validate('lexisone_citation_search-20100116 .xml')
>       self.expectMsg(u'OpenSearch: <ShortName> element too long')

tests/test_validator.py:295:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.test_validator.SearchTools testMethod=test_opensearch_shortname>, msg = 'OpenSearch: <ShortName> element too long'

    def expectMsg(self, msg):
>       assert msg in self.messages, (
                    'Expected %r but only got %r' % (msg, self.messages))
E       AssertionError: Expected u'OpenSearch: <ShortName> element too long' but only got [u'Test']
E       assert 'OpenSearch: <ShortName> element too long' in ['Test']
E        +  where ['Test'] = <tests.test_validator.SearchTools testMethod=test_opensearch_shortname>.messages

tests/test_validator.py:107: AssertionError
_____________________________________________________________________________________________________ SearchTools.test_too_many ______________________________________________________________________________________________________

self = <tests.test_validator.SearchTools testMethod=test_too_many>

    def test_too_many(self):
        self.validate('addon-12201-latest.xml')
>       self.expectMsg(u'OpenSearch: Too many <ShortName> elements')

tests/test_validator.py:299:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.test_validator.SearchTools testMethod=test_too_many>, msg = 'OpenSearch: Too many <ShortName> elements'

    def expectMsg(self, msg):
>       assert msg in self.messages, (
                    'Expected %r but only got %r' % (msg, self.messages))
E       AssertionError: Expected u'OpenSearch: Too many <ShortName> elements' but only got [u'Test']
E       assert 'OpenSearch: Too many <ShortName> elements' in ['Test']
E        +  where ['Test'] = <tests.test_validator.SearchTools testMethod=test_too_many>.messages

tests/test_validator.py:107: AssertionError
=============================================================================================== 3 failed, 669 passed in 278.03 seconds ===============================================================================================
ERROR: InvocationError: '/Users/awagner/mozilla/amo-validator/.tox/py27/bin/py.test tests/'
______________________________________________________________________________________________________________ summary _______________________________________________________________________________________________________________
ERROR:   py27: commands failed
```

Why don't I see that detailed output in travis?

**Comment by diox** [comment]
I'm getting `MemoryError` for those tests. Plus they take a very long time. IMHO they should be kept separate from the unit tests...

**Comment by wagnerand** [comment]
I couldn't get pytest to recognize them as proper tests if they were not in the `tests/` directory. `py.test functional_tests` raised import errors for `amo.validate` for example. Does pytest handle the `tests/` directory in a special way?

**Comment by wagnerand** [comment]
Ok, fixed by adding `functional_tests/__init__.py`. Thanks for the hint.

@diox could you give this another r?, please?

**Comment by diox** [comment]
r+

**Comment by wagnerand** [comment]
Sweet, thank you!

**Pull request merged**
