### PR TITLE
Flag all instances of mozFetchAsStream for Firefox 43

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1226306

### CODE REVIEW

**Comment by magopian** [comment]
Looks good to me. @mstriemer would you mind giving this a quick look?

**Comment by EnTeQuAk** [comment]
@mstriemer while figuring out what this app_versions thing is, I found that it might be appropriate to do something like https://gist.github.com/EnTeQuAk/ce68acc558edd6db158f but I don't know about real world implications :confused:

**Comment by mstriemer** [comment]
Looks good. r+

As far as changing the way the app versions are set I wouldn't worry about it. I normally add 5 of them at a time which takes a few minutes and is good for most of a year. I agree that it is strange but long live addons-validator!

**Comment by EnTeQuAk** [comment]
hehe, alrighty. Thanks @mstriemer :smiley:

**Pull request merged**
