### PR TITLE
Bug 1164836: Fix the resolution of chrome content packages pointing to '/'

### PR DESCRIPTION
**Pull request by kmaglione**

### CODE REVIEW

**Comment by magopian** [comment]
@mstriemer could you please have a quick look too?

**Comment by magopian** [comment]
(bonus points for fixing the flake8 errors in a separate commit, easier to review :+1: )

**Comment by magopian** [comment]
I believe this is to fix http://sentry.mktmon.services.phx1.mozilla.com/mkt/addonsmozillaorg/group/15975/ ?

**Comment by kmaglione** [comment]
It's to fix that error, yes.

**Comment by kmaglione** [comment]
I believe all comments have been addressed. Can someone have another look?

**Comment by magopian** [comment]
This looks perfect, but for a minor nit, thanks!

r+wc

**Pull request merged**
