### PR TITLE
Bug 1179490: Don't strip \\u and \\x escapes from scripts before parsing JS.

### PR DESCRIPTION
**Pull request by kmaglione**

### CODE REVIEW

**Comment by magopian** [comment]
Do we have a clue why we had that in the first place?

**Comment by magopian** [comment]
Missing a test

**Comment by kmaglione** [comment]
I don't know why we had it, no. I tracked down an older revision with this comment:

```py
    code = unicodehelper.decode(code)
    # Acceptable unicode characters still need to be stripped. Just remove the
    # slash: a character is necessary to prevent bad identifier errors.
    return JS_ESCAPE.sub("u", code)
```

But it doesn't make sense, and everything works as expected (and all tests pass) without this mangling.

**Comment by kmaglione** [comment]
Added test.

**Comment by magopian** [comment]
r+, thanks!

**Comment by wagnerand** [comment]
@magopian @kmaglione merge?

**Pull request merged**
