### PR TITLE
Add newest jquery versions to known hashes

### LINKED ISSUE #387: jQuery 2.2.0 is unknown version
The latest version in fetcher is 2.1.4:

https://github.com/mozilla/amo-validator/blob/master/extras/jslibfetcher.py

But default version to download from jQuery is 2.2.0 now:

https://code.jquery.com/
https://jquery.com/download/

I think it should be added to JQUERY_VERSIONS

### PR DESCRIPTION
**Pull request by wagnerand**
Fix #387

### CODE REVIEW

**Comment by tofumatt** [comment]
r+

**Comment by wagnerand** [comment]
Thanks!

**Comment by ArtemAvramenko** [comment]
Please tell when these changes are moved to https://addons.mozilla.org ?

**Comment by tofumatt** [comment]
We deploy once a week on Thursday. So you should see these in production sometime Thursday after 9am Pacific Time.

**Pull request merged**
