### PR TITLE
Warn for latest angularjs library only

### PR DESCRIPTION
**Pull request by wagnerand**

### CODE REVIEW

**Comment by tofumatt** [comment]
Because the rest aren't allowed, they'll just fail, right? This means the latest one is allowed but warns users to upgrade?

**Comment by wagnerand** [comment]
Self r+  👀

**Comment by wagnerand** [comment]
Oh, github didn't update the page for me :)

Yes, there was a slight misunderstanding of what the actual policy should be. We should disallow all old versions, allow the most recent one (for the time being) but warn developers and editors about it.

**Comment by tofumatt** [comment]
Cool, all good then (r+)

**Comment by wagnerand** [comment]
Thank you.

**Pull request merged**
