### PR TITLE
Update links to point to github

### PR DESCRIPTION
**Pull request by wagnerand**
Note: This makes us lose the template unless we use https://github.com/blog/2111-issue-and-pull-request-templates but that would make it the default for all newly filed issues.

r?

### CODE REVIEW

**Comment by muffinresearch** [comment]
I wonder if we should consider directing user-bug reports to mozilla/addons instead of mozilla/addons-server. Just because we're going to get more repos in the not too distant so a bug for AMO will not necessarily mean it's addons-server. 

We could add the templates there instead. This would mean that user bugs would need to be referenced from the repo where the fix is being made but cross-project referencing for github issues does work well so that shouldn't be an issue.

**Comment by tofumatt** [comment]
That's an interesting notion. It means addons becomes a place of bug triage and we might need to re-file bugs (though because we have edit permissions we can easily just copy a user's original markdown and move the contents to a new bug easily--or just reference the original bug).

I'm cool with that idea. Savvy users can still file bugs in components as they please, but it prevents novices from getting bogged down in minutia when they just want to report something. :+1:

**Comment by muffinresearch** [comment]
Yeah I think referencing is likely to be nicer than having to copy & paste.

**Comment by muffinresearch** [comment]
@wagnerand OK let's go for pointing to mozilla/addons for issues. I'll sort out something for the readme there.

**Comment by wagnerand** [comment]
Done.

**Pull request merged**
