### PR TITLE
update app_versions.json

### PR DESCRIPTION
**Pull request by magopian**

### CODE REVIEW

**Comment by myrdd** [comment]
the changes look ok

**Comment by mstriemer** [comment]
:+1: r+

**Comment by mstriemer** [comment]
Actually, do we want SeaMonkey up to `2.42`?

**Comment by magopian** [comment]
@mstriemer no clue ;) I'm taking the info from https://addons.mozilla.org/en-US/firefox/pages/appversions/

**Comment by magopian** [comment]
I'll merge as is, we'll still be able to complete later if needed.

**Pull request merged**
