### PR TITLE
Flag 'xpinstall.signatures.required'

### PR DESCRIPTION
**Pull request by wagnerand**
r?

### CODE REVIEW

**Comment by mstriemer** [comment]
It looks like this will add a high-severity warning which means that the add-on will still be auto-signed if it is unlisted. Should this be an error instead?

**Comment by mstriemer** [comment]
I guess you could get around this check so it's fine as a warning.

**Comment by wagnerand** [comment]
I agree. The pref will be gone soon anyway, but in the meantime, we need to raise awareness for reviewers during the review.

**Comment by mstriemer** [comment]
r+

**Comment by wagnerand** [comment]
Thanks!

**Pull request merged**
