### PR TITLE
Bug 1355891: Simplify Marionette prefs check to catch all Marionette …

### PR DESCRIPTION
**Pull request by AutomatedTester**
…prefs.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Does this catch anything in particular that it didn't before? If so, can we add a test for it?

**Comment by AutomatedTester** [comment]
@EnTeQuAk Test is already there in https://github.com/mozilla/amo-validator/blob/master/tests/test_regex.py#L16-L26

The prefs in the validator are no longer used and so simplifying to just the top level

**Comment by wagnerand** [comment]
If they are no longer used, why not just remove them?

**Comment by AutomatedTester** [comment]
@wagnerand because the prefs in the validator are not used. There are new ones hence this pull request.

@muffinresearch can we get this landed?

**Comment by muffinresearch** [comment]
@wagnerand would you have time to land this and cut a release, and update addons-server to use it? Or alternatively if you can point me to docs on the package release process I can get it done.

**Pull request merged**
