### PR TITLE
Fail for add-ons built with cfx

### PR DESCRIPTION
**Pull request by wagnerand**
r? @mstriemer

### CODE REVIEW

**Comment by mstriemer** [comment]
I briefly skimmed this and it looks reasonable but I really didn't get a good look.

Can you add a functional test that a real XPI from cfx fails?

**Comment by wagnerand** [comment]
Test added.

**Comment by mstriemer** [comment]
r+

I'm hoping this has been communicated somehow through compatibility or blog posts or something? Seems like something that could catch a lot of people by surprise.

**Comment by wagnerand** [comment]
I suggested writing a blog post. For now, we have https://developer.mozilla.org/en-US/Firefox/Releases/44 and https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/cfx

**Pull request merged**
