### PR TITLE
Accept the new type 128 in install.rdf (bug 1220583)

### PR DESCRIPTION
**Pull request by magopian**
Fixes [bug 1220583](https://bugzilla.mozilla.org/show_bug.cgi?id=1220583)

### CODE REVIEW

**Comment by magopian** [comment]
@mstriemer r?

**Comment by mstriemer** [comment]
Should these get flagged for admin review initially? Is it safe to treat them as regular extensions on initial submission since we have nothing preventing any user from submitting it?

**Comment by magopian** [comment]
We'll be preventing users from submitting on AMO: see [bug 1220715](https://bugzilla.mozilla.org/show_bug.cgi?id=1220715)

**Comment by mstriemer** [comment]
If there is something that prevents experiments from being accepted on AMO right now then I'm r+. This should wait for that to be merged though.

**Comment by magopian** [comment]
Oh definitely, I'll hold on merging this until we have the code in AMO. Thanks for the review!

**Comment by magopian** [comment]
@mstriemer ok I've implemented amo's side with https://github.com/mozilla/olympia/pull/889 and https://github.com/mozilla/olympia/pull/890, would you like to have a look?

**Pull request merged**
